env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    rom_name: "ENCRYPTED[!76e956716c2b472a50930f541eb8ecd10ea6752ce4b0c8faf1208dfb8ec3702cfab10ea10265f852f217f4ba5afb4c55!]"
    device: lavender
    script: "ENCRYPTED[!e2929dc97e9272e972873395cda9960d737abccb0e940d6b9356cff569a400daba27e5b47ba72619b81da2749137a4d6!]"
    ght: "ENCRYPTED[!616bfef24eafbd26238c00272434caa03215da3dd1f362cd1509a6980858f21fb999da7c56a6c8d4bd5aaddfbcc6204c!]"

task:
  name: test
  timeout_in: 4h
  container:
      image: snaxpsycho/cirrus:latest
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus:/home/cirrus
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
  notify_script: bash <(curl -s $script/sync.sh)
  test_script: bash <(curl -s $script/build.sh)